services:
  backend:
    image: ${IMAGE:-ghcr.io/pkiraly/qa-catalogue-slim:main}
    volumes:
      - ./${INPUT:-input}:/opt/qa-catalogue/input
      - ./${OUTPUT:-output}:/opt/qa-catalogue/output
      - ./${LOGS:-logs}:/opt/qa-catalogue/logs
      - ./${WEBBCONFIG:-web-config}:/var/www/html/qa-catalogue/config
      - /etc/timezone:/etc/timezone:ro    # Sync timezone
      - /etc/localtime:/etc/localtime:ro  # Sync localtime
    container_name: ${CONTAINER:-metadata-qa-marc}
    command: /opt/qa-catalogue/qa-catalogue
