# docker-compose.yml for qa-catalogue-web (frontend)

services:
  app:
    image: ${FRONTEND_IMAGE:-qa-catalogue-web}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./${BASE_OUTPUT_DIR:-output}:/var/www/html/metadata-qa
      - ./${WEB_CONFIG:-webconf}:/var/www/html/config
    ports:
      - ${WEBPORT:-80}:80
    container_name: ${FRONTEND_CONTAINER:-qa-catalogue-web}
    extra_hosts:
      qa-catalogue-solr: ${SOLR_HOST_IP}
