# docker-compose.yml for qa-catalogue-web (frontend)

services:
  frontend:
    image: ${FRONTEND_IMAGE:-ghcr.io/pkiraly/qa-catalogue-web:main}
    volumes:
      - ./${OUTPUT:-output}:/var/www/html/metadata-qa
      - ./${WEB_CONFIG:-web-config}:/var/www/html/config
    ports:
      - ${WEBPORT:-80}:80
    container_name: ${FRONTEND_CONTAINER:-qa-catalogue-web}
    extra_hosts:
      qa-catalogue-solr: ${SOLR_HOST_IP}
