#!/usr/bin/bash
set -euo pipefail

source default.env

# dependencies
docker pull $FRONTEND_IMAGE
docker pull $SOLR_IMAGE

# no backend-only docker image yet, so we use sources
if [ -d qa-catalogue ]; then git -C qa-catalogue pull ; else git clone https://github.com/pkiraly/qa-catalogue.git; fi
mkdir -p input; [ -L qa-catalogue/input ] || ln -s ../input qa-catalogue/input
mkdir -p output; [ -L qa-catalogue/output ] || ln -s ../output qa-catalogue/output

# TODO: install dependencies (php, sqlite3, R...)

cd qa-catalogue
mvn clean install


# allow Solr in Docker to write directory
# mkdir -p solrdata

# TODO: this is only required once and after updates!

# start solr container
# docker compose --env-file default.env -f solr.yml up
