# docker-compose.yml for solr

services:
  solr:
    image: ${SOLR_IMAGE}
    ports:
      - ${SOLR_PORT:-8983}:8983
    volumes:
      - ./${SOLR_DATA:-solrdata}:/var/solr
      - ./solrconf:/opt/solr/server/solr/configsets/_default:ro
    command: /opt/solr/server/solr/configsets/_default/solr-init.sh
    container_name: ${SOLR_CONTAINER:-qa-catalogue-solr}
