# docker-compose.yml for solr

services:

  # initialize and run solr
  solr:
    depends_on:
      - solrdata
    image: ${SOLR_IMAGE}
    ports:
      - ${SOLR_PORT:-8983}:8983
    volumes:
      - ./${SOLR_DATA:-solrdata}:/var/solr
      - ./solrconf:/opt/solr/server/solr/configsets/_default:ro
    command: /opt/solr/server/solr/configsets/_default/solr-init.sh
    container_name: ${SOLR_CONTAINER:-qa-catalogue-solr}

  # make sure the solrdata directory is owned by user solr (8983)
  solrdata:
    image: alpine
    container_name: solrdata
    restart: no
    entrypoint: /bin/sh -c "chown 8983:8983 /solr"
    volumes:
      - ./${SOLR_DATA:-solrdata}:/solr


