# docker-compose.yml for solr

services:
  solr:
    image: ${SOLR_IMAGE}
    ports:
      - ${SOLR_PORT:-8983}:8983
    user: 1000:1000 # TODO: don't hardcode
    volumes:
      - ./${SOLR_DATA:-solrdata}:/var/solr
      - ./solr-init.sh:/solr-init.sh:ro
      - ./solrconf:/opt/solr/server/solr/configsets/_default
    command: /solr-init.sh
    container_name: ${SOLR_CONTAINER:-qa-catalogue-solr}
